# Generated by Django 4.0.6 on 2022-07-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cvMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_menu_name', models.CharField(blank=True, max_length=50)),
                ('m_menu_ıcon', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
