# Generated by Django 4.0.6 on 2022-07-15 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Education_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Informations_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=50)),
                ('p_surname', models.CharField(blank=True, max_length=50)),
                ('p_about', models.TextField(blank=True)),
                ('p_picture', models.ImageField(blank=True, upload_to='')),
                ('p_birth_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_experience_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('job_description', models.TextField(blank=True)),
                ('job_position', models.CharField(blank=True, max_length=100)),
                ('job_start_date', models.DateField(blank=True)),
                ('job_end_date', models.DateField(blank=True)),
                ('still_working', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Educations_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_name', models.CharField(blank=True, max_length=50)),
                ('edu_start_date', models.DateField(blank=True)),
                ('edu_ended_date', models.DateField(blank=True)),
                ('edu_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cv.education_types')),
            ],
        ),
        migrations.CreateModel(
            name='Certifications_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certifica_name', models.CharField(blank=True, max_length=150)),
                ('certifica_url', models.CharField(blank=True, max_length=250)),
                ('certifica_qualification_id', models.CharField(blank=True, max_length=250)),
                ('certifica_start_date', models.DateField(blank=True)),
                ('certifica_ended_date', models.DateField(blank=True)),
                ('certifica_image', models.ImageField(blank=True, upload_to='')),
                ('certifica_company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cv.courses')),
            ],
        ),
    ]
