# Generated by Django 4.0.6 on 2022-07-15 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifications_me',
            name='certifica_ended_date',
        ),
    ]
