# Generated by Django 4.0.6 on 2022-07-17 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_abilities_sub_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_abilities',
            name='parent_ability',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='cv.abilities'),
            preserve_default=False,
        ),
    ]
