# Generated by Django 4.0.6 on 2022-07-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_sub_abilities_parent_ability'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_media_name', models.CharField(blank=True, max_length=50)),
                ('s_media_url', models.URLField(blank=True, max_length=150)),
                ('s_media_icon', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
